ARG IMAGE_NAME=dustynv/ros:humble-ros-base-l4t-r32.7.1

FROM ${IMAGE_NAME}

ARG ZED_SDK_MAJOR=4
ARG ZED_SDK_MINOR=0
ARG ZED_SDK_PATCH=7
ARG JETPACK_MAJOR=4
ARG JETPACK_MINOR=6
ARG L4T_MAJOR=32
ARG L4T_MINOR=6

ARG ROS2_DIST=humble       # ROS2 distribution
    
# ZED ROS2 Wrapper dependencies version
#ARG XACRO_VERSION=2.0.8
#ARG DIAGNOSTICS_VERSION=3.1.2
#ARG AMENT_LINT_VERSION=0.12.4
#ARG GEOGRAPHIC_INFO_VERSION=1.0.4
#ARG ROBOT_LOCALIZATION_VERSION=3.4.2

ARG XACRO_VERSION=2.0.9
ARG DIAGNOSTICS_VERSION=3.1.2
ARG AMENT_LINT_VERSION=0.16.1
ARG GEOGRAPHIC_INFO_VERSION=1.0.5
ARG ROBOT_LOCALIZATION_VERSION=3.6.0

ENV DEBIAN_FRONTEND noninteractive

# Disable apt-get warnings
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 42D5A192B819C5DA || true && \
  apt-get update || true && apt-get install -y --no-install-recommends apt-utils dialog && \
  rm -rf /var/lib/apt/lists/*
  
ENV TZ=America/New_York

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \ 
  apt-get update && \
  apt-get install --yes lsb-release wget less udev sudo build-essential cmake python3 python3-dev python3-pip python3-wheel git jq libpq-dev zstd usbutils && \    
  rm -rf /var/lib/apt/lists/*

## Update g++ and gcc to 11
RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
 apt install -y gcc-11 && \
 apt install -y g++-11 &&\
 update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 11 && \
 update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11 && \
 update-alternatives --config gcc && \
 update-alternatives --config g++ 

# Copy files from your host to your current working directory
COPY ZED_SDK_Tegra_L4T32.7_v4.0.8.zstd.run .

# Install the ZED SDK
RUN python3 -m pip install --upgrade pip
RUN echo "# R${L4T_MAJOR} (release), REVISION: ${L4T_MINOR}" > /etc/nv_tegra_release && \
  apt-get update -y || true && \
  apt-get install -y --no-install-recommends zstd wget less cmake curl gnupg2 \
  build-essential python3 python3-pip python3-dev python3-setuptools libusb-1.0-0-dev -y && \
  pip install protobuf && \
  sudo chmod +x ZED_SDK_Tegra_L4T32.7_v4.0.8.zstd.run && \
    ./ZED_SDK_Tegra_L4T32.7_v4.0.8.zstd.run -- silent skip_tools && \
  rm -rf /usr/local/zed/resources/* && \
  rm -rf ZED_SDK_Tegra_L4T32.7_v4.0.8.zstd.run && \
  rm -rf /var/lib/apt/lists/*

    
# Install the ZED ROS2 Wrapper
ENV ROS_DISTRO ${ROS2_DIST}

# Install the ZED ROS2 Wrapper
WORKDIR /root/ros2_ws/src

#RUN git clone --recursive https://github.com/stereolabs/zed-ros2-wrapper.git
RUN git clone --recursive https://github.com/olaghattas/zed-ros2-wrapper.git

# Install missing dependencies
WORKDIR /root/ros2_ws/src
RUN wget https://github.com/ros/xacro/archive/refs/tags/${XACRO_VERSION}.tar.gz -O - | tar -xvz && mv xacro-${XACRO_VERSION} xacro && \
  wget https://github.com/ros/diagnostics/archive/refs/tags/${DIAGNOSTICS_VERSION}.tar.gz -O - | tar -xvz && mv diagnostics-${DIAGNOSTICS_VERSION} diagnostics && \
  wget https://github.com/ament/ament_lint/archive/refs/tags/${AMENT_LINT_VERSION}.tar.gz -O - | tar -xvz && mv ament_lint-${AMENT_LINT_VERSION} ament-lint && \
  wget https://github.com/cra-ros-pkg/robot_localization/archive/refs/tags/${ROBOT_LOCALIZATION_VERSION}.tar.gz -O - | tar -xvz && mv robot_localization-${ROBOT_LOCALIZATION_VERSION} robot-localization && \
  wget https://github.com/ros-geographic-info/geographic_info/archive/refs/tags/${GEOGRAPHIC_INFO_VERSION}.tar.gz -O - | tar -xvz && mv geographic_info-${GEOGRAPHIC_INFO_VERSION} geographic-info && \
  cp -r geographic-info/geographic_msgs/ . && \
  rm -rf geographic-info && \
  git clone https://github.com/ros-drivers/nmea_msgs.git --branch ros2 && \
  git clone https://github.com/ros/angles.git --branch humble-devel
  

# Check that all the dependencies are satisfied
WORKDIR /root/ros2_ws
RUN apt-get update -y || true && rosdep update && \
  rosdep install --from-paths src --ignore-src -r -y && \
  rm -rf /var/lib/apt/lists/*

# Install cython
RUN python3 -m pip install --upgrade cython

# Build the dependencies and the ZED ROS2 Wrapper
RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/install/setup.bash && \
  colcon build --parallel-workers $(nproc) \
  --event-handlers console_direct+ --base-paths src \
  --cmake-args ' -DCMAKE_BUILD_TYPE=Release' \
  ' -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs' \
  ' -DCMAKE_CXX_FLAGS="-Wl,--allow-shlib-undefined"' \
  ' --no-warn-unused-cli' "

WORKDIR /root/ros2_ws

# Setup environment variables
COPY ros_entrypoint_jetson.sh /sbin/ros_entrypoint.sh
RUN sudo chmod 755 /sbin/ros_entrypoint.sh

ENTRYPOINT ["/sbin/ros_entrypoint.sh"]
CMD ["bash"]

